[workspace]
members = [
    "wasmple",
    "wasmple_bridge",
    "wasmple_bridge_attribute",
    "wasmple_bridge_impl",
    "wasmple_buffer",
    "wasmple_buffer_derive",
    "wasmple_console",
]

[profile.release]
opt-level = "z"
lto = true
