[package]
name = "wasmple"
description = "a sample project for WebAssembly with Rust & SolidJS."
version = "0.1.2"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
lto = true

[dependencies]
