[package]
name = "wasmple_console"
description = "a sample project for WebAssembly with Rust & SolidJS."
version = "0.3.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
lto = true

[dependencies]
once_cell = "1.15.0"
