[package]
name = "wasmple_console"
description = "a sample project for WebAssembly with Rust & SolidJS."
version = "0.4.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
once_cell = "1.15.0"

[dev-dependencies]
rstest = "0.15.0"
