name: delivery to cloudflare pages

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      rust-target: wasm32-unknown-unknown
      node-version: 16.x
    steps:
      - uses: actions/checkout@v3
      - name: use node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
      - name: rust target ${{ env.rust-target }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ env.rust-target }}
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}
      - run: cargo install wasm-snip
        continue-on-error: true
      - run: npm install
      - run: npm run clean
        if: github.ref == 'refs/heads/main'
      - run: npm run build
      - name: publish to cloudflare pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: wasmple
          directory: ./dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
