name: check and test

on: pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      rust-target: wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: rust target ${{ env.rust-target }}
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ env.rust-target }}
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}
      - run: bun install
      - run: bun run check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ runner.os }}
      - run: bun install
      - run: bun run test
